-- ─────────────────────────────────────────────────────────────────────────────
-- 20260614000002_open_coverage.sql
--
-- Open coverage (broadcast) on swap_requests:
--   1. Allow target_user_id = NULL on swap_requests
--   2. Extend kind CHECK to include 'open'
--   3. Add partial unique index: at most one open/pending request per occurrence
--   4. RPC request_coverage — assignee broadcasts "anyone take this?"
--   5. RPC claim_coverage   — any eligible member atomically claims the open request
-- ─────────────────────────────────────────────────────────────────────────────

-- ── 1. Allow target_user_id = NULL ───────────────────────────────────────────
-- Open coverage requests have no specific target; target is filled in on claim.

ALTER TABLE public.swap_requests
  ALTER COLUMN target_user_id DROP NOT NULL;

-- ── 2. Extend kind CHECK to allow 'open' ─────────────────────────────────────
-- Drop the constraint added in swap_v2 and replace it with an extended one.
-- (The constraint name was generated by Postgres from the column expression.)

ALTER TABLE public.swap_requests
  DROP CONSTRAINT IF EXISTS swap_requests_kind_check;

ALTER TABLE public.swap_requests
  ADD CONSTRAINT swap_requests_kind_check
  CHECK (kind IN ('outbound', 'volunteer', 'open'));

-- ── 3. One open/pending request per occurrence ────────────────────────────────
-- Postgres treats two NULLs as distinct in a unique index, so the existing
-- swap_requests_no_dup_pending index would allow multiple open requests from
-- the same requester on the same occurrence. We add a separate partial unique
-- index to enforce the "at most one open/pending per occurrence" invariant.

CREATE UNIQUE INDEX swap_requests_one_open_per_occ
  ON public.swap_requests (occurrence_id)
  WHERE kind = 'open' AND status = 'pending';

-- ── 4. request_coverage ───────────────────────────────────────────────────────
-- Caller (current assignee) broadcasts an open coverage request.
-- Does NOT vacate the assignee — they still own it until someone claims it.
--
-- Note: open requests (target_user_id=NULL) cannot be actioned by respond_swap
-- because respond_swap checks `target_user_id IS DISTINCT FROM auth.uid()` which
-- is always TRUE when target_user_id is NULL. This is intentional — open requests
-- must be claimed via claim_coverage, not respond_swap.

CREATE OR REPLACE FUNCTION public.request_coverage(
  p_occurrence_id uuid,
  p_message       text DEFAULT NULL
)
RETURNS public.swap_requests
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = public
AS $$
DECLARE
  v_occ  occurrences;
  v_swap swap_requests;
BEGIN
  SELECT * INTO v_occ FROM occurrences WHERE id = p_occurrence_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'occurrence not found';
  END IF;

  -- Caller must be the current assignee
  IF v_occ.assigned_user_id IS DISTINCT FROM auth.uid() THEN
    RAISE EXCEPTION 'not authorized: only the current assignee can request coverage';
  END IF;

  IF v_occ.status != 'scheduled' THEN
    RAISE EXCEPTION 'coverage only allowed on scheduled occurrences';
  END IF;

  IF v_occ.scheduled_at <= now() THEN
    RAISE EXCEPTION 'coverage only allowed on future occurrences';
  END IF;

  -- Check for existing open/pending request (the unique index will also catch
  -- this, but we give a friendlier error message).
  IF EXISTS (
    SELECT 1 FROM swap_requests
    WHERE occurrence_id = p_occurrence_id
      AND kind = 'open'
      AND status = 'pending'
  ) THEN
    RAISE EXCEPTION 'an open coverage request already exists for this occurrence';
  END IF;

  IF p_message IS NOT NULL AND char_length(p_message) > 200 THEN
    RAISE EXCEPTION 'message must be 200 characters or fewer';
  END IF;

  INSERT INTO swap_requests (occurrence_id, requester_id, target_user_id, message, kind)
  VALUES (p_occurrence_id, auth.uid(), NULL, p_message, 'open')
  RETURNING * INTO v_swap;

  PERFORM pg_notify('rotini_occurrence_changed', jsonb_build_object(
    'occurrence_id', p_occurrence_id,
    'rota_id',       v_occ.rota_id,
    'event',         'coverage_requested'
  )::text);

  RETURN v_swap;
END;
$$;

GRANT EXECUTE ON FUNCTION public.request_coverage(uuid, text) TO authenticated;

-- ── 5. claim_coverage ─────────────────────────────────────────────────────────
-- Any non-viewer rota member (other than the requester) may claim an open
-- coverage request. The UPDATE WHERE status='pending' is the atomic race gate:
-- the first caller wins; subsequent callers get 0 rows → 'already taken'.

CREATE OR REPLACE FUNCTION public.claim_coverage(
  p_swap_request_id uuid
)
RETURNS public.occurrences
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = public
AS $$
DECLARE
  v_swap         swap_requests;
  v_occ          occurrences;
  v_caller_role  text;
  v_old_assignee uuid;
BEGIN
  SELECT * INTO v_swap FROM swap_requests WHERE id = p_swap_request_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'swap request not found';
  END IF;

  IF v_swap.kind != 'open' THEN
    RAISE EXCEPTION 'claim_coverage is only for open coverage requests';
  END IF;

  -- Requester cannot claim their own request
  IF v_swap.requester_id = auth.uid() THEN
    RAISE EXCEPTION 'not authorized: you cannot claim your own coverage request';
  END IF;

  SELECT * INTO v_occ FROM occurrences WHERE id = v_swap.occurrence_id;

  -- Caller must be an active (owner/member) rota member — viewers are excluded
  SELECT role INTO v_caller_role
  FROM rota_members
  WHERE rota_id = v_occ.rota_id AND user_id = auth.uid();

  IF NOT FOUND OR v_caller_role NOT IN ('owner', 'member') THEN
    RAISE EXCEPTION 'not authorized: you are not an eligible member of this rota';
  END IF;

  -- Snapshot the current assignee before the race-gate UPDATE
  v_old_assignee := v_occ.assigned_user_id;

  -- Atomic race gate: first writer wins
  UPDATE swap_requests
  SET status     = 'accepted',
      target_user_id = auth.uid(),
      decided_at = now()
  WHERE id = p_swap_request_id
    AND status = 'pending'
  RETURNING * INTO v_swap;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'already taken';
  END IF;

  -- Update the occurrence: assign to claimer, preserve original_assignee_id
  UPDATE occurrences
  SET assigned_user_id     = auth.uid(),
      original_assignee_id = COALESCE(original_assignee_id, v_old_assignee),
      status               = CASE WHEN status = 'open' THEN 'scheduled' ELSE status END
  WHERE id = v_swap.occurrence_id
  RETURNING * INTO v_occ;

  -- Cancel all other pending swaps on this occurrence (outbound/volunteer/open)
  UPDATE swap_requests
  SET status = 'cancelled', decided_at = now()
  WHERE occurrence_id = v_swap.occurrence_id
    AND id != p_swap_request_id
    AND status = 'pending';

  PERFORM pg_notify('rotini_occurrence_changed', jsonb_build_object(
    'occurrence_id', v_swap.occurrence_id,
    'rota_id',       v_occ.rota_id,
    'event',         'coverage_claimed'
  )::text);

  RETURN v_occ;
END;
$$;

GRANT EXECUTE ON FUNCTION public.claim_coverage(uuid) TO authenticated;
